import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faMapMarkerAlt,
  faPhone,
  faEnvelope,
} from "@fortawesome/free-solid-svg-icons";
import styles from "../styles/components/Contact.module.css";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Ian&apos;s Granite and Marble Installations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.contact}>
        <div className={styles.container}>
          <h2 className={styles.page_title}>Get a quote</h2>
          <div className={styles.info_container}>
            <a href="tel:868-620-4109" className={styles.info}>
              <FontAwesomeIcon icon={faPhone} className={styles.icon} />
              <i className={styles.text}>868-620-4109</i>
            </a>

            <a href="tel:868-789-3346" className={styles.info}>
              <FontAwesomeIcon icon={faPhone} className={styles.icon} />
              <i className={styles.text}>868-789-3346</i>
            </a>

            <a
              href="https://www.google.com/maps/place/Ian's+Granite+and+Quartz+Installations,/@10.5706531,-61.4085915,17z/data=!3m1!4b1!4m5!3m4!1s0x8c35ff7539d4f245:0x93294760a66f285a!8m2!3d10.5706945!4d-61.4072741"
              className={styles.info}
            >
              <FontAwesomeIcon icon={faMapMarkerAlt} className={styles.icon} />
              <i className={styles.text}>#106 Bejucal Road Cunupia</i>
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
